//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoUPC.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espacio
    {
        public Espacio()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int EspacioId { get; set; }
        public bool Ocupado { get; set; }
        public int PisoId { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int Ancho { get; set; }
        public int Alto { get; set; }
    
        public virtual Piso Piso { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
