//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoUPC.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int UsuarioId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string DniUsuario { get; set; }
        public int TipoUsuarioId { get; set; }
        public string UsuarioL { get; set; }
        public string Password { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
