//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoUPC.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int VentaId { get; set; }
        public int UsuarioId { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime FechayHoraAlquilerInicio { get; set; }
        public Nullable<System.DateTime> FechayHoraAlquilerSalida { get; set; }
        public int EspacioId { get; set; }
        public bool EstadoPago { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Espacio Espacio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
